export const EMOJI: {[key: string]: string} = {
	gold: '💰',
	wood: '🌲',
	stone: '⛏',
	food: '🍖',
	gem: '💎',
	karma: '☯',
	wins: '🎖',
	terra: '🗺',
	people: '👥',
	army: '⚔',
	archer: '🏹',
	listLeader: '👑',
	listNormal: '🔅',
	listYou: '⚜',
	buildings: '🏘',
	workshop: '⚒',
	townhall: '🏤',
	storage: '🏚',
	houses: '🏘',
	farm: '🌻',
	sawmill: '🌲',
	mine: '⛏',
	barracks: '🛡',
	wall: '🏰',
	repair: '⚒',
	trebuchet: '⚔',
	ballista: '⚔',
	war: '⚔',
	search: '🔎',
	alliancebattle: '🕊',
	attack: '⚔',
	defence: '🛡',
	trade: '🎪',
	castle: '🏰',
	dragon: '🐲',
	undead: '☠'
}
